# Site settings
title: JoElla Carman
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A place for charts and graphs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: carman_copy
github_username:  joellacarman

# Build settings
markdown: kramdown
future: true
